# For GCP
runtime: go114

service: api-sqlite

# F1 gets 28 free hours/day vs B which gets 9/day (probably upgrade to B later)
# https://cloud.google.com/appengine/quotas
instance_class: F1

# FIXME: not production ready
automatic_scaling:
  max_instances: 1

# Insecure!
env_variables:
  SQLITE_FILEPATH: ":memory:"
  RSA_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJJwIBAAKCAgEA7q4R3soRD2CrjL13OK6YSBG8wpjP5sbfkL0QhpJMH87grlR2
    SS3CUnbYCOONzQiJ3OuKAViy/lMw1KsmG9NnhAot2acg1iNyZRY33LR2jwmfFF+2
    iRp0itPQeOHY6GS8m3WLCMtC/kWUq0Bl5g1PYa9JXwSkTTRJunNH0TPk8uqwFeVh
    pT336M1H6ed105L8a8W3mpSwlwePron7pLf7wD32m9RT0nNdnHBDQCsUKS/Gdp+s
    aLYWTgj0rpnQCe8f1p3g36Gm0gTzr3X0Adow8gIPfxO4HU/0cdL+Pw4mpcsWJ453
    1taRLLGb+a2la2zAUteYcS+8d4Nb8Omkbz39PylvKP6R1kHElqlF3BnwUp0AdcAv
    OLdeX8kYUlbKE8xwjHm/KwwleKlcAZDam7hCRw72JUQiod0E7My+SiZ3Ij5zKnxZ
    XmAF5BX8T+YSqSzR4Qdp2QU9L9GgAZo/HPBNwME9v8usjEzrEItSSg3Nn10+J+yg
    sCqjrCT8CnSvD8wEyDSdO/Jly9DnWJ6B2HJEOc4wxWGFTCE0wiQOwC3IPNxFhuWu
    n6/4tsEQcDs5XHaBXIHry5WCiVkjwa2pc95xiXcfoQWr1A/jLe/MrZyN4yrgDK9m
    mQxxNzVfLj8S9NPjJMv+K7BKvtOmvoqsf13K6hYJGkAdR0d99DNFlllRm7cCAwEA
    AQKCAgAe7zSluW7InXDehtfi4s4d2R6r4f5gHLpxGfAAYQm4vallLtE93s5mvbx2
    OnfwcQDdPzHdxs88IzAbACuqQ5YRCPi0UvLwjhuPene3BTSwiUCy9UzFLEaaj6Vf
    ZXYleJjxVSS1+RIvvnjsUSZj0KnPMVbDF+jrkLFVlwdh1+X+jehQjjA/qG5vH9wI
    NtWQnGZW2YNYZ5kTmglHR97zlFzup5lEzRooFoe1dN9ie7LbO7PvP/aqg58Uchi0
    YH8UKofn2wKAOYVThwzGWvVLICpj01yKzdV5BxnZfs0xAvaDWnT+n3psv9aFAmgC
    zjy4VZn/oq3BTbyRiNbrvHxxZolh3Dhuq0ByIPgvLsJ3jBpcrZaufnRxDXG+zmD4
    OKP7vOVoNs1TdZ/s/2lKZDoqmQ9TzV+/gJ4u6Gd+XSKj4iwkNu7Nuspbdv+jfkMQ
    JugdcCKcdOLfmy0oeE3O57Mf/arc5BDhDD6vgEyushM+gmGrImmpigvbFuCMleHi
    BxCgGNkg8FIycQkErir4/PZWyPG+0jkRURkVH6BrOiPptBW8CpNEK6E7b6RLmiLw
    Rw8KUEwXVqFx4aLcicGv2jN5TvrRheUo8ekbdQpnn82naYQmJH/qJuEQgAMyzgef
    vYNtwEPmxu4W1P8MgsXY5sXqaZutmWoAar5H40sApB6WWaJ44QKCAQEA/CJUtmGy
    uQrz6Xd9/eIAQ1zwqKrCI9RqU79IA/mTxunRShNvfezunlM6U+81Y9l6T36KiWz4
    Fz54vWW2GHEi7lNapXsb+BI1JL2dOh9Hk8IsdTgbyVcvij4/tMFsbg36y7xLmmXg
    DTnWcAsjkUrmTB+a/2w69yg1uwJJHV0CdkYVvjM3asOu336TL9T79Tvz9R3dIsGY
    JoRFTuOVH6j2uXARK4eJ3vJXjceo+3vWcG+SpIejO6dnoT4QjwEQP/0hnU+bVEvX
    ExkI+xz/Cm3OdqsAtWfwbBnEu6dEyB7LmXyWruZGt8VGuE/gd/FgnFwcXbyi2m5K
    LwVWQXzrr+jTuQKCAQEA8lbt2WyOTcOTtiwXJTiNi2MkAqITD6B+xH/XVxaIEoMF
    Ulgt/pjnnUJ4WUsoBpfKYD3kYLlqKWcCqIrCUtwnH8+fU/Etz3nY1qVHQen3rqOr
    bIp0Dh/g4+pAEqNfWdZUm9G13IiQbleA6QIN53+aYgxohw1dEWA7sLpJDug6vXI2
    AWFvbPJKiZ8L9ZjqvE7dggk3Yo62TwgqiV1x0kiADcHoSdASeZHgqgPttNIJcwok
    7EGaXTWLEL1wJMQhuLtl1xRaHCAc3rcTlupqisjefp5VIUJekpt56bOjoO6jPV1c
    ikpqF4H8531VpU1Rhh3f1KQs/eyiRQzIKlkElvCC7wKCAQA+nvQ1O/ycksjTonbr
    WHdCQ9INwiNnrLkfxbFIM3NtguMVJ9CYEQGO1xL0h8PV4czL85zK1wKjG0P3nkxk
    s6y+TnuEABiJO1RxpJppNh2b6C0Mi/vyvLG0/xLpfOTGTLiOY1zPox/LiSLmPw39
    ZwHdxDfF2oamnhkCMmYgYdpbr7p0u9m2rZVAMvqxdY+Cb/p+VYV3vWdhoZZpKoL+
    EwP8OIY7LnWipsPyFbW1iCNRV5SvQnTbOw+072pDajsz+VWg8YWdoRxwxNYDMEdz
    uqP9uyj45TDEWH4RMVEW9vcQTu5J0C2eNOQEoOoaQBwDmaj96vzzjVLlbMjoiPMs
    hIIZAoIBAFWXhFxVrhEjMYmXGvmndr6zXmWbrtXHHt7yNDFrINZA9mE2CdCxWqS9
    dFo9ZD6n3++MDJxpAGjtHBBBKg8v+JWQtDpmpYJxC7gMGhXauAMzhXlJkWHnuntl
    IgozL5tASxPZxrzEcxa1yy8A7b5E4FcfANAqVSOs9Igf02vzc8OzkgV8z2kQTmk7
    BnNQ9h9aT3v9G1WxCAzz2mo32dqmhqvVP+DKH6xWbJ4/0vYZdQLvo0jahtXC8oIQ
    Foq1xx9C+N41LvpeETRMPxv/YW/xMDxSWcjscxCe3zk+nF1by8YBsoyZac0xuQxd
    xSEkJNYUuRiWf9mTeWCf+haS6D8TZXsCggEANb6KXWR9CSOZoidSQEmqsdu8oQ5j
    7iB/2CneFImUWdLxj+b36/2nnYaPTvQZQ/UlqfYnMC4hK21LOM1mSf3PW2jkva8+
    5kfkb2PpnSqHL0SzIZpaYo9bCZtApaOkQqxIlQNBKgBPZfUNxaFFGEUqse0/+Qnq
    tAWkWYooYKccZkiXLxOYv+70/gpEQU46AywXDY2GaD5TJYh/fTvgMJhnv+8p5MAv
    LVKtT3nuo5tMBDJ0xueMerDLlDfG1ScqiOR49lOFY3d5XnriA9TSk1HJCoOEC+1X
    sqKfTOsmb5oxxy2+OAa516sHPF1UKHJm6V3p28IHISt+hyurEnUEFwgtVw==
    -----END RSA PRIVATE KEY-----

